language: python
sudo: false
env:
    - TOXENV=doc8
    - TOXENV=flake8
    - TOXENV=pep257
    - TOXENV=py27
install:
    - pip install tox
script:
    - tox -e $TOXENV
matrix:
    fast_finish: true
